### ISSUE TITLE
Repo checklist 

### ISSUE THREAD

**Issue by hopeyen** [graphops/subfile-data-service#27]
Before open sourcing

- [x]  `README.md`
- [x]  Has `CONTRIBUTORS.md` guide
- [x]  Has `SECURITY.md`
- [x]  Has Pull Request Template
- [x]  Has `CODE_OF_CONDUCT.md`
- [x]  License (any public work must be licensed Apache 2)
- [x]  CD to automatically build and push any artifacts (Docker Images, Helm Charts, binary blobs, etc)
- [x]  Has automated release/changelog generation
- [x]  Has commit hooks that enforce (via husky)
- [x]  Has been added to admin repo public list if public
- [x]  Has a description and tags
- [x]  The repo has decent documentation for users

**Comment by hopeyen** [comment]
User docs: a185f1d28f3a7e39fa21acfc4467ecd811f3b5da, 212c01cc4d27ee8c1eebfbfc7981c1c7a5b94d4d, 
misc docs: 08a7030121fb1ce7b3029efdb3b5b70d802873b9
release script: e793778989e46c8e1fe664848551d44bc8863d59
templates: 3fd7515d150e4e032bd78e5a76ec9496766de8e1
commit hook: f4076c0533c3a7d92754b6efeab3e43f235fb22e
workflows: d889146795d094919d29d548f63e30c434bc9fb9
admin repo: https://github.com/graphops/admin/pull/34
