### ISSUE TITLE
Tracking: on-chain transactions

### ISSUE THREAD

**Issue by hopeyen** [graphops/subfile-data-service#31]
**Problem statement**

Missing on-chain components. The original plan was to wait for protocol v2 but we might as well go ahead exploring the options to make it compatible with v1.

**Expectation proposal**

Options to be compatible with protocol v1
- Allocation based on subfiles 
- Allocation based on an IPFS file to an indexer url

Create a Transaction manager entity that 
- [x] Allows the Publisher to deploy an IPFS hash on-chain
~- [ ] Server registers its URL~
- [x] Add a CLI for the server for allocation management https://github.com/graphops/subfile-data-service/issues/36
  - [x] send an `allocate` transaction against the IPFS hash -> Get allocation_id
  - [x] send an `close` transaction against the IPFS hash with 0x POI
- [x] Service payment collection 
  - [x] require moving service to indexer-rs framework  https://github.com/graphops/subfile-data-service/issues/30
  - [ ] send `redeem` tx to Escrow contracts (This should be handled by indexer-agent https://github.com/graphprotocol/indexer/pull/831
- [x] Client wallet query payments https://github.com/graphops/subfile-data-service/issues/21
  - [x] sends deposit transactions - identify indexers as receivers
  - [x] Receipt Signer
  - [x] Send receipts in query requests (chunking wrt to package sizes and budget)

**Comment by hopeyen** [comment]
Start with staking contract that enables on-chain transactions `allocate` and `closeAllocation`
and Escrow contract that enables `deposit`, `depositMany`, and `redeem`
